version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  api-mock:
    build: .
    container_name: api-mock-container
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    depends_on:
      - mongodb
    environment:
      - ENVIRONMENT=local
      - MONGO_URI=mongodb://mongodb:27017/api_mock_db
      - DATABASE_NAME=api_mock_db
      - SECRET_KEY=sua_chave_secreta_super_segura_aqui
    restart: always

volumes:
  mongodb_data:
