# sonar-project.properties

# Chave única do projeto no Sonar (pode ser o nome do repositório)
sonar.projectKey=BrubsMarcelle_api-mockup-data
sonar.organization=bmg-dev
sonar.projectName=API Mockup Data
sonar.projectVersion=1.0

# Caminho para o código fonte (pasta onde está o código da API)
sonar.sources=app
# Exclusões (pastas que o Sonar não deve analisar para qualidade)
sonar.exclusions=**/venv/**, **/.venv/**, Dockerfile, .github/**, .gitignore, requirements.txt, .env, .env.example, sonar-project.properties, .logs/**, docker-compose.yml, LICENCE, README.md

# Caminho para a pasta de testes
sonar.tests=tests

# Configurações de Cobertura de Código (Python)
sonar.python.version=3.11
# Caminho do arquivo XML de cobertura gerado pelo pytest-cov
sonar.python.coverage.reportPaths=coverage.xml

# Codificação
sonar.sourceEncoding=UTF-8
