apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-mockup-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: SecretStore
  target:
    name: api-secrets
    creationPolicy: Owner
  data:
  - secretKey: SECRET_KEY
    remoteRef:
      key: api-mockup-secret-key
  - secretKey: MONGO_URI
    remoteRef:
      key: api-mockup-mongo-uri
