apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-mockup-data-sa
  annotations:
    # Exemplo para Workload Identity (Azure/GCP)
    azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000"
